// Code generated by goctl. DO NOT EDIT.
package types

type OrderAddRequest struct {
	Sno      string `json:"sno"`                //流水号
	Model    string `json:"model,optional"`     //型号
	Num      int64  `json:"num,optional"`       //
	Category int64  `json:"category,default=1"` //1:未打印流号号，2当日已打印的流水号
}

type AddResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type OrderAddPrintedRequest struct {
	Barcode string `json:"barcode"`
}

type OrderListReq struct {
	PageSize int64 `form:"pageSize"`
	Category int64 `form:"category"` //1:未打印流号号，2当日已打印的流水号
}

type OrderListResp struct {
	List []string `json:"list"`
}
